"use client"

import { useState } from "react"
import { Button } from "@/components/ui/button"
import { Textarea } from "@/components/ui/textarea"
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card"
import { Volume2, Loader2, AlertCircle } from "lucide-react"
import { useAuth } from "@/contexts/auth-context"
import { createClientSupabaseClient } from "@/lib/supabase"
import { useToast } from "@/components/ui/use-toast"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select"
import { allVoices, getDefaultVoice } from "@/lib/voice-options"
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert"
import SyncAudioPlayer from "@/components/sync-audio-player"

interface SentenceTimestamp {
  text: string
  start: number
  end?: number
}

export default function TextToSpeechPage() {
  const [text, setText] = useState("")
  const [title, setTitle] = useState("")
  const [selectedVoice, setSelectedVoice] = useState(getDefaultVoice().id)
  const [audioUrl, setAudioUrl] = useState<string | null>(null)
  const [sentenceTimestamps, setSentenceTimestamps] = useState<SentenceTimestamp[]>([])
  const [isGenerating, setIsGenerating] = useState(false)
  const [error, setError] = useState<string | null>(null)
  const [isFallbackAudio, setIsFallbackAudio] = useState(false)
  const { user, isConfigured } = useAuth()
  const { toast } = useToast()
  const supabase = createClientSupabaseClient()

  const generateSpeech = async () => {
    if (!text.trim()) {
      setError("Please enter text content")
      return
    }

    try {
      setIsGenerating(true)
      setError(null)
      setIsFallbackAudio(false)
      setAudioUrl(null)
      setSentenceTimestamps([])

      // 找到选中的语音选项
      const voice = allVoices.find((v) => v.id === selectedVoice) || getDefaultVoice()

      // 使用服务器端API生成语音
      const response = await fetch("/api/text-to-speech", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
        },
        body: JSON.stringify({
          text,
          voice: voice.id,
          languageCode: voice.languageCode,
        }),
      })

      // 检查响应状态
      if (!response.ok) {
        let errorMessage = "Failed to generate audio"
        try {
          const errorData = await response.json()
          errorMessage = errorData.error || errorData.details || errorMessage
        } catch (e) {
          // 如果响应不是JSON格式，使用状态文本
          errorMessage = `Server error: ${response.status} ${response.statusText}`
        }
        throw new Error(errorMessage)
      }

      // 解析JSON响应
      let data
      try {
        data = await response.json()
      } catch (e) {
        throw new Error("Server returned invalid JSON data")
      }

      if (!data.audioUrl) {
        throw new Error("Server did not return audio URL")
      }

      setAudioUrl(data.audioUrl)

      // 设置句子时间戳（如果有）
      if (data.sentenceTimestamps && Array.isArray(data.sentenceTimestamps)) {
        setSentenceTimestamps(data.sentenceTimestamps)
      } else {
      }

      // 检查是否使用了备用音频
      if (data.fallback) {
        setIsFallbackAudio(true)
        toast({
          title: "Using Sample Audio",
          description: data.message || "Google TTS temporarily unavailable, using sample audio instead",
          variant: "warning",
        })
      }

      // 如果用户已登录且 Supabase 已配置，保存到历史记录
      if (user && supabase && !data.savedToHistory) {
        const { error: saveError } = await supabase.from("audio_history").insert({
          user_id: user.id,
          text_content: text,
          audio_url: data.audioUrl,
          title: title || `Audio generated by ${voice.name}`,
          // 保存时间戳数据
          timestamps: data.sentenceTimestamps ? JSON.stringify(data.sentenceTimestamps) : null,
        })

        if (saveError) {
          console.error("Error saving to history:", saveError)
          toast({
            title: "Failed to save history",
            description: "Your audio was generated but could not be saved to history.",
            variant: "destructive",
          })
        } else {
          toast({
            title: "Audio Generated",
            description: "Saved to your history.",
          })
        }
      }
    } catch (err) {
      setError(err instanceof Error ? err.message : "Error generating audio, please try again")
      console.error(err)
    } finally {
      setIsGenerating(false)
    }
  }

  // 下载音频文件
  const downloadAudio = () => {
    if (!audioUrl) return

    const link = document.createElement("a")
    link.href = audioUrl
    link.download = `${title || "speech"}_${new Date().toISOString().slice(0, 10)}.mp3`
    document.body.appendChild(link)
    link.click()
    document.body.removeChild(link)
  }

  return (
    <div className="container max-w-3xl py-10">
      <Card>
        <CardHeader>
          <CardTitle className="text-2xl">Text to Speech</CardTitle>
          <CardDescription>Convert your text to speech. Paste your text and click the generate button</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          {user && (
            <div className="space-y-2">
              <Label htmlFor="title">Title (Optional)</Label>
              <Input
                id="title"
                placeholder="Add a title for your audio"
                value={title}
                onChange={(e) => setTitle(e.target.value)}
              />
            </div>
          )}

          <div className="space-y-2">
            <Label htmlFor="voice">Language Options</Label>
            <Select value={selectedVoice} onValueChange={setSelectedVoice}>
              <SelectTrigger>
                <SelectValue placeholder="Select a language" />
              </SelectTrigger>
              <SelectContent>
                {allVoices.map((voice) => (
                  <SelectItem key={voice.id} value={voice.id}>
                    {voice.name}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          <div className="space-y-2">
            <Label htmlFor="text">Text Content</Label>
            <Textarea
              id="text"
              placeholder="Paste the text you want to convert to speech here..."
              className="min-h-[200px] resize-y"
              value={text}
              onChange={(e) => setText(e.target.value)}
            />
          </div>

          {error && (
            <Alert variant="destructive">
              <AlertCircle className="h-4 w-4" />
              <AlertTitle>Error</AlertTitle>
              <AlertDescription>{error}</AlertDescription>
            </Alert>
          )}

          <div className="flex justify-end">
            <Button onClick={generateSpeech} disabled={isGenerating || !text.trim()} className="w-full sm:w-auto">
              {isGenerating ? (
                <>
                  <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  <Volume2 className="mr-2 h-4 w-4" />
                  Generate Audio
                </>
              )}
            </Button>
          </div>

          {audioUrl && (
            <div className="mt-6">
              <h3 className="text-lg font-medium mb-2">Your Audio is Ready</h3>

              {isFallbackAudio && (
                <Alert className="mb-4">
                  <AlertCircle className="h-4 w-4" />
                  <AlertTitle>Using Sample Audio</AlertTitle>
                  <AlertDescription>Google TTS service is temporarily unavailable. Currently using sample audio instead. Please try again later.</AlertDescription>
                </Alert>
              )}

              {/* 传递API返回的时间戳到同步播放器 */}
              <SyncAudioPlayer
                audioUrl={audioUrl}
                text={text}
                sentenceTimestamps={sentenceTimestamps}
                onDownload={downloadAudio}
              />

              {!user && (
                <div className="mt-4 p-3 bg-primary/10 rounded border border-primary/20 text-sm">
                  <p>Login or register to save your audio history!</p>
                  <div className="flex gap-2 mt-2">
                    <Button variant="outline" size="sm" asChild>
                      <a href="/login">Login</a>
                    </Button>
                    <Button size="sm" asChild>
                      <a href="/register">Register</a>
                    </Button>
                  </div>
                </div>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  )
}
